service:
  servlet:
    context-patch: /vendas-ms/api
    

spring:
  datasource: 
    url: jdbc:h2:mem:testdb
    username: sa
    password:
      driverClassNameame: org.h2.Driver

h2:
  console: 
    enabled: true
    path: /h2-console